### ISSUE TITLE
Software template for Keycloak

### ISSUE THREAD

**Issue by davgordo** [halkyonio/assemble-platforms#4]
As an Assemble contributor or demo'er
I want a Keycloak software template
So that I can spin a Keycloak instance to use for Backstage authentication

Acceptance:

Automatically provision operator
Automatically provision instance
Automatically provision service accounts / RBAC

**Comment by cmoulliard** [comment]
> software template

Is there a definition/description about what is a `software template` ? Why do you want to spin an instance using k8s resources, chart, etc instead of using a controller or application on the platform able to provision such a service, app from a package + parameters using the input of the user ? Delegating such a work on the platform could simplify the work to maintain for assemble tens of yaml, templates, ... WDYT ? @davgordo

**Comment by davgordo** [comment]
Thanks for your thoughts @cmoulliard I agree that the way this automation is packaged could be re-imagined. Helm is a convenient way for us to express the components we need in the short term, and I have an idea to compose as a "chart of charts" (just for now) to collect parameters in one place for someone installing the platform. I have a feeling that maintaining this "master chart" is not sustainable. An operator or controller of some kind could nicely encapsulate platform operations. I hope that short term scaffolding with a GitOps controller + Helm templating at least helps to inform later implementations.

**Comment by davgordo** [comment]
closed by #18
